import type { Metadata } from "next";
import "./globals.css";
import EthereumProviders from "../contexts/EthereumProviders";
import Link from "next/link";
import { ConnectButton } from "@rainbow-me/rainbowkit";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-blue-50 text-blue-900">
        <main className="container mx-auto pt-20 pb-40 px-20">
          <EthereumProviders>{children}</EthereumProviders>
        </main>
      </body>
    </html>
  );
}
